# -*- coding: utf-8 -*-
"""9_DA_ProbabilityDistribution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p0IB-Ch5c7coOqvlVCQ_2ImWqJCPC1eP

#Probability Distribution

### Binomial Distribution
"""

from scipy.stats import binom #scientific python - binomial 
import matplotlib.pyplot as plt #Graph,charts

num_trials = 10
heads_probability = .5

probs = [binom.pmf(i, num_trials, heads_probability) for i in range(11)] #probability mass function
plt.stem(list(range(11)), probs)

"""### Poisson distribution"""

from scipy.stats import poisson
rate = 3.3

probs = [poisson.pmf(i, rate) for i in range(15)] #probability mass function
plt.stem(list(range(15)), probs)