# -*- coding: utf-8 -*-
"""6_DA_ExploringMeanMedianQuartile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14V-crBo1pixITB9XdLA1d_-ddr95W6iF

###6_Exploring Mean, Median, Quartile

### Import Library
"""

import pandas as pd #useful for loading the dataset

"""### Load Dataset from Local Directory"""

from google.colab import files
uploaded = files.upload()

"""### Load Dataset"""

dataset = pd.read_csv('Dataset.csv')
datasetwithNaN = dataset
dataset

"""### Load Summarize"""

print(dataset.shape)
print(dataset.describe())

"""###Checking for NaN Values"""

dataset.isna().any()

"""### Filling NaN values with the Mean  
###Problem - New value becomes high coz of outlier (Large value scale)
"""

MeandatasetNotNan = dataset.price.fillna(dataset.price.mean())
MeandatasetNotNan

"""### Solution - Filling NaN value with Median"""

MediandatasetNotNan = dataset.price.fillna(dataset.price.median())
MediandatasetNotNan

"""###Identifying and removing the outlier - Huge difference in value 

"""

dataset.describe()

percentile = dataset.price.quantile(1.0)
percentile

datasetNoOutlier = dataset[dataset.price<percentile]
datasetNoOutlier