# -*- coding: utf-8 -*-
"""PythonBasics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzap28PXRT98GPPEsgOPN3mcH_RDWqGX

# Python Basics
"""

print ("Hello Champs")

"""### Variable & Types"""

z = 5.4
print(type(z))

# Commented out IPython magic to ensure Python compatibility.
a = 5
b = "Champ"
c = [1,2,3]
d = 5.2
# %whos

'''a = 5
b = "Champ"
c = [1,2,3]'''
d = 5.2
del d

"""# Operator - Arithmetic"""

a=10
b=5
print("a+b: ",a+b)
print("a-b: ",a-b)
print("a/b: ",a/b)
print("a%b: ",a%b) #
print("a*b: ",a*b)
print("a//b: ",a//b)
print("a**b: ",a**b) #pow(a,b) #power

"""# Operator -  Boolean"""

a=False
b=True
print(type(a))
print(type(b)) 
print((a and b) != (a or b))

"""# Operator - Comparison"""

x=10
y=5
print("x less than y: ",x<y)
print("x greater than y: ",x>y)
print("x equivalent to y: ",x==y)
print("x not equal to y: ",x!=y)
print("x less than or equal to y: ",x<=y)
print("x greater than equal to y: ",x>=y)

"""#Getting Input from user"""

name = str(input("Enter your name: "))
yearofbirth = int(input("Enter your year of Birth: "))
height = float(input("Enter your Height: "))
print("Name: {0}| YearOfBirth: {1}| Height: {2}".format(name,yearofbirth,height))

"""# If Condition"""

a = 5
b = 5
if a<=b:
  print("a is less than b")
elif a==b:
  print("a is equal to b")
  print("a is not less than b")
  print("a is not greater than b")
else:
  print("a is greater than or equal to b")

"""# While """

i = 0
while i<5:
  print(i)
  i+=1 #i=i+1

i = 1
while True:
  if i%10 !=0:
    print("Checking...")
    i+=1
    continue
  print("If-Completed")
  break
print("Completed")

"""# For """

for i in range(5):
  print(i)

for i in range(1,10,2):
  print(i)

for i in range(10,1,-3):
  print(i)

"""# List"""

numList = []
for i in range (1,10):
  print(i)
  numList.append(i*16)
print(numList)

strList = {"Name":"sanjay","YOB":1996,"Weight":67}
for i in strList:
  print(i, strList[i])

"""# Functions"""

def display():
  print("Hello Champs")
  print("Hai")

display()

def arith(a,b):
  sum = a+b
  diff = a-b
  div = a/b
  print("ADD: {0}, SUB: {1}, DIV: {2}".format(sum,diff,div))

var1 = int(input("Enter 1st Number: "))
var2 = int(input("Enter 2nd Number: "))
arith(var1,var2)

def arith(a,b):
  sum = a+b
  diff = a-b
  div = a/b
  return sum,diff,div

var1 = int(input("Enter 1st Number: "))
var2 = int(input("Enter 2nd Number: "))
result = arith(var1,var2)
print(result)
print("Difference: ",result[1])

def arith(*data):
  sum=0
  for i in range(len(data)):
    sum = sum+data[i]
  return sum

a=5
b=2
c=3
print("Total: ",arith(a,b,c))

def info(**data):
  for i in data:
    print("Variable Name is:",i)
    print("Variable Value is:", data[i])

info(x="Sanjay",b=24)

def typeCheck(valuee):
  if isinstance(valuee,str):
    print("It is String")
  else:
    print("It is Number")
var = 100
typeCheck(var)

"""# String"""

data = "Hello Champs"

print(len(data)) #length of data
print(data[2]) #letter by its index
print(data[:6]) #Until Indexx
print(data[3:]) #From Index
print(data[1:11]) #From & To Index
print(data[::-1]) #reverse by index

data2 = " Hello,Champs " #data = 12:10:50
strippedData = data2.strip() #remove spaces in beginning and end
print(strippedData)
cleanData = strippedData.split(",") #Split data based on Delimitter
print(cleanData)
print(cleanData[0])
print(cleanData[1].upper()) #Changing into uppercase
print(cleanData[1].lower()) #Changing into lowercase
print(cleanData[1].capitalize()) #Changing into lowercase
print(strippedData.replace (",","*********")) #replacing